#pragma once

#define TAPPING_TERM 200

#define PERMISSIVE_HOLD

#define MOUSEKEY_MAX_SPEED 4
#define MOUSEKEY_TIME_TO_MAX 90
#define MOUSEKEY_INTERVAL 4
#define MOUSEKEY_DELAY 50

#define RGB_DI_PIN D3
#define RGBLED_NUM 9
#define RGBLIGHT_ANIMATIONS
